### ISSUE TITLE
Freeze external dependencies 

### ISSUE THREAD

**Issue by nosnibor89** [leonardoas10/hangman-game#1]
Instead of telling developer which dependencies to install, we can just version the list of dependencies and install from requirement.txt. 
See https://pip.pypa.io/en/stable/cli/pip_freeze/

**Comment by leonardoas10** [comment]
Thanks for the info. This is the [commit](https://github.com/leonardoas10/hangman-game/commit/a8b5e23c956d913ce11408351ad4f0fe9506fcbb)
